### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#1]
E.g. fix mobile theme QR after taking picture.

![Screenshot_20190605-211818](https://user-images.githubusercontent.com/6080900/58985662-2e3fd180-87dc-11e9-8dd8-ccaad0830636.jpg)

**Comment by andi34** [comment]
QR from Gallery is fine after https://github.com/andi34/photobooth/commit/c239718b93a86bcbb9c20f295cc534a46dd48c1b

![Screenshot_20190605-211608](https://user-images.githubusercontent.com/6080900/58985781-6b0bc880-87dc-11e9-9f2b-6377dba078a2.jpg)

**Comment by andi34** [comment]
@F4bsi ne Idee?

**Comment by F4bsi** [comment]
@andi34 Besteht das Problem noch?
Müsste mich auch erstmal wieder reinfuchsen. Denke am Wochenende hätte ich wieder ein bisschen Zeit. 
Meistens ist aber in dem Fall das Problem, dass im CSS die Kombination aus `position: abolute;` und `left: 50%; margin-left: -XXXpx; ` genutzt wird. Durch den festen Wert passt es nur auf Desktops / größeren Devices. Umgehen kann man das meistens mit `transform: translate(-50%, -50%);` oder halt in den Media Querys

**Comment by andi34** [comment]
Super, vielen Dank nochmal. Habe gestern stundenlang versucht es hinzubekommen, aber am Ende war es ein riesen weisse Fläche mit kleinem QR und dafür dann auch in der Galerie nicht mehr schön 🙈 raffe auch nicht warum der QR mit seiner Größe überhaupt sozusagen 2x definiert ist...

**Comment by andi34** [comment]
Ready for review https://github.com/andreknieriem/photobooth/pull/78
