### ISSUE TITLE
Bug: gallery settings not saved from admin panel

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#11]
Only the date format can be saved from admin panel.
Checkboxes from gallery get ignored, it always uses saved config from config.inc.php.

All other checkboxes work fine (general, wedding etc.)

Need to investigate further, no quick fix found.

**Comment by andi34** [comment]
Fixed https://github.com/andi34/photobooth/commit/0a8c874e5ad5fa93f9c1eb61b9b8746954d2f313

**Comment by tobiashaas** [comment]
Also bei mir wird es nicht gespeichert ... Hab es jetzt mehrfach heruntergeladen und neu draufgepackt! Dev und Master...
Email, Galerie und Hochzeit speichert er nicht

**Comment by andi34** [comment]
Komisch. Bei mir läuft es auf Buster und auf Xubuntu LTS.

Hast du die config.js vorher gelöscht?

**Comment by andi34** [comment]
Ggf auch einmal neustarten den Pi.

**Comment by andi34** [comment]
Im Zweifel auch:
```
sudo usermod -a -G www-data Pi
```

**Comment by tobiashaas** [comment]
> Komisch. Bei mir läuft es auf Buster und auf Xubuntu LTS.
> 
> Hast du die config.js vorher gelöscht?

Die Config wars ..... die hatte ich vergessen zu löschen! Jetzt passt es
Danke dir

**Comment by andi34** [comment]
Sehr gut :) freut mich :)

Nur noch Kleinigkeiten, dann gibt's auch die Filter. 🥳

Wann ist die Hochzeit wo du die Box nutzen willst?

**Comment by tobiashaas** [comment]
Die Hochzeit war bereits am 13.7 ;-) 
Hab dieses Jahr aber noch 2 Hochzeiten von Freunden wo ich die Box gerne aufstellen würde! 

Hat sich bei knapp 200 Fotos mal aufgehängt.
Ich suche aktuell noch nach einer Möglichkeit, bei einem Touchscreen in Chromium, die Zoom Funktion zu deaktivieren. Die Box lies sich nicht mehr bedienen nachdem jemand reingezoomt hat... ;-)

**Comment by tobiashaas** [comment]
Auf die Filter bin ich gespannt! <3

**Comment by andi34** [comment]
Mobile Seite? Oder über die Desktop Seite?
Da kein responsive Design erzwingt es in meinem tree die desktop Seite nun.

**Comment by andi34** [comment]
Ansonsten:
```
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
<meta name='apple-mobile-web-app-capable' content='yes' />
```

**Comment by tobiashaas** [comment]
Auf der Desktop Seite

**Comment by tobiashaas** [comment]
![GitHawk Upload by tobiashaas](https://i.imgur.com/I1f8fXO.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tobiashaas** [comment]
Auf der Mobilen Seite - auf meinem iPhone XS - ist die Galerie nicht nutzbar.

**Comment by andi34** [comment]
Die Ansicht liegt daran, das die Booth nicht für mobile Geräte geschrieben ist. Auf der Desktop Seite sollte alles aussehen wies soll.

Responsive Design ist ne Sache.... Aber sehr aufwendig und alleine schaffe ich das nicht. Dafür bin ich nicht weit genug mit meinen Kenntnissen.
Teile sind ja auch im core.js hinterlegt und garnicht nur über die style.css definiert. Macht es nicht einfacher.

**Comment by andi34** [comment]
Fork deaktivert fix den Zugriff auf den button?

**Comment by tobiashaas** [comment]
Mir reicht die Desktop Seite, wollte dich nur darauf hinweisen ;-)
Ne der Fork ist nicht der Übeltäter

**Comment by tobiashaas** [comment]
Ich muss mich auch mal bisschen mehr in die Thematik reinfuchsen.
Möchte auch mehr helfen können! ;-)

**Comment by andi34** [comment]
Responsive Design ist auf meiner Liste ;)

Bis dahin:
Kannst natürlich die Schrift in der index.php anpassen. Aus ```<H1>``` z.B. ```<h2>``` machen oder gar ```<p>```

Dann sollte auch mehr Schrift in eine Zeile passen ;)

**Comment by andi34** [comment]
Ist leider auch so ziemlich alles sehr abhängig von der Display Größe...

**Comment by andi34** [comment]
Versuche immer alles in logischen commits hochzuladen. 
So lerne ich immer: Anschauen was wird wie umgesetzt. Ist es ein logischer commit der nur eine Sache macht ist vieles einfach nachvollziehbar. Würde ich alles in einen commit packen und "Update" nennen hast du tausend teile die du verstehen musst.

Mache das seit Jahren so im Android Bereich auch und bin damit schon weit gekommen.

**Comment by tobiashaas** [comment]
Wäre es eigentlich nicht sinnvoller, wenn man das einfach an ein fertiges Framework anpasst, welches komplett Reponsive ist? 
Hab heute mal ein bisschen gegoogelt und bin auf solche Frameworks gestoßen 😉
https://www.keycdn.com/blog/front-end-frameworks

Liebe Grüße 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andi34** [comment]
Kein plan, wie viel Mehrarbeit oder Wenigerarbeit das ist 😅

**Comment by tobiashaas** [comment]
Wenn ich die Tage mal Zeit habe schaue ich mir das mal genauer an ;-) dass ich auch mal wieder was dazu beitragen kann 🙈

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andi34** [comment]
Sollte das meiste mit den Media querys im style.css gehen. Im Browser lässt sich ja auch eine Gerätegröße einstellen und somit am PC anpassen möglich sein .
