### ISSUE TITLE
Syncing photos to external drive (also backup)

### ISSUE THREAD

**Issue by thatonedude3470** [andi34/photobooth#113]
**Is your feature request related to a problem? Please describe.**
Currently there is no default way of backing up photos from the photobooth to an external drive (e.g. USB or HDD) despite manually coping them, 

**Describe the solution you'd like**
My idea was to have a drop down in the admin to select a drive, then if a drive is selected a cronjob could rsync the files onto it periodically.

**Describe alternatives you've considered**
For Linux there are udev rules that could be triggered once a mountable drive was inserted, but that doesn't port to Windows (maybe there are ways for Windows to achieve the same).

**Comment by andi34** [comment]
Not sure if there's a good way to do it without security impacts. I'd not like to give to much permissions to the www-data user.
What about running e.g. [freefilesync](https://freefilesync.org/) in background?
Or setting up a cron job on Linux to copy files from location a to location b?

I've been working on a solution to download the data folder as zip from disc-usage page , but not got it working last time I've forward ported it to latest version (need to look at it again as it worked when I started working on it).

**Comment by thatonedude3470** [comment]
Not sure how much permissions lsblk needs, but the selection could be realized with it (newer version can also export to JSON see [systeminformation](https://github.com/sebhildebrandt/systeminformation/blob/1dd402812396d35b6007b497263dc712f1c347ba/lib/filesystem.js#L754)).
The selected drive name could then be written to the/a config file and then read from a script that gets executed via a cronjob. (cronjob triggers script every 5 mins -> script reads which drive to use -> mount drive if not mounted yet -> copy files). 
In that manner the script won't be executed from the www-data user. 

Could the zip solution also be offered to visitors? You got me interested there now.

**Comment by andi34** [comment]
> Not sure how much permissions lsblk needs, but the selection could be realized with it (newer version can also export to JSON see [systeminformation](https://github.com/sebhildebrandt/systeminformation/blob/1dd402812396d35b6007b497263dc712f1c347ba/lib/filesystem.js#L754)).
> The selected drive name could then be written to the/a config file and then read from a script that gets executed via a cronjob. (cronjob triggers script every 5 mins -> script reads which drive to use -> mount drive if not mounted yet -> copy files).
> In that manner the script won't be executed from the www-data user.
> 

Currently I've only limited time to work on the Photobooth and there's some stuff left on my to-do list first.
Maybe you've time to work on a solution?
Else I'll take a look at it at some point later.

> Could the zip solution also be offered to visitors? You got me interested there now.

Once there's something ready to test yes :)

**Comment by thatonedude3470** [comment]
Sure, understandable. I'll take a spin at it and open a PR once it's stable :)


> Once there's something ready to test yes :)

Really looking forward to it! Guess it will come with some password option?

**Comment by thatonedude3470** [comment]
Tested on a fresh Raspberry PI install and it worked without any issues. Synced all the files in data folder to a USB stick.
Only issue I could see for now is that the cronjob gets added to root and thus the script called by root, due to the install script being executed as root.
The script works without root privileges, so maybe we could/should redirect the crontab call to another user?
But for now that should do it :)

**Comment by andi34** [comment]
> Could the zip solution also be offered to visitors? You got me interested there now.

https://github.com/andi34/photobooth/pull/125
