### ISSUE TITLE
vertical scrolling neccessary on Galaxy Tab S2 in Chroma-Key-Editing

### ISSUE THREAD

**Issue by danielh84** [andi34/photobooth#139]
**Describe the bug**
With the Galaxy Tab S2 (1024x762, Device-Pixel-Ratio:2) you get an vertical scrollbar by editing pictures with chroma key (chromakeying.php?filename=20201121_125652.jpg). Maybe the main picture should be smaller to get everything on the tablet without scrolling. You cant see the "save" and "close" buttons without scrolling:
![grafik](https://user-images.githubusercontent.com/19638140/99877535-358cb200-2bff-11eb-987f-110505cb4b19.png)

**To Reproduce**
1. Use Ratio of the Galaxy Tab S2
2. Go to "Gallery" and use "Chroma Key"-Button
3. See error

**Expected behavior**
You have to see the save and close Buttons without scrolling. 

**Environment (please complete the following information):**
 - Android
 - Fully Kiosk Browser

**Photobooth**
- Which version of Photobooth are you using? -> Develop-branch 21.11.2020

**Comment by andi34** [comment]
Hey and sorry for the late reply.

You can try to lower the width here:
https://github.com/andi34/photobooth/blob/3c6a7bcdc5897c727abfb06d3fc1e4afa3f67ae3/src/sass/chromakeying.scss#L23-L29

**Comment by danielh84** [comment]
width: 850px; works fine with this device. 

i will try to find a css-config that it will fit to all resolutions. maybe there is a good opinion.

**Comment by andi34** [comment]
Something like

```
@media (max-height: 765px) {
  .canvasWrapper {
    width: 850px;
  }
}
```
Maybe?

**Comment by andi34** [comment]
@danielh84 can you try from `feature/livekeying` branch?

**Comment by danielh84** [comment]
no, does not work. Tested with classic and modern styling

**Comment by andi34** [comment]
After https://github.com/andi34/photobooth/pull/159 you're allowed to use your custom style

Needs all of them to work (can be copy of existing files):
```
template/custom.template.php
resources/css/custom_style.css
resources/css/custom_chromakeying.css
resources/css/custom_live_chromakeying.css
```

**Comment by andi34** [comment]
Any progress on the css changes to not affect all resolutions?
