### ISSUE TITLE
Allow to deactivate standalone picture

### ISSUE THREAD

**Issue by GeoffreyV** [andi34/photobooth#155]
**Is your feature request related to a problem? Please describe.**

It's not

**Describe the solution you'd like**

For some events, I'd like to force people to take only collage and don't want them to be able to take standalone photo. 

**Additional context**

I already added some conditions and the related item in the admin panel on my forked branch and alpha tested it. I'm not sure yet how to handle the physical button since for now a long press is needed to take a collage. 
Work in progress.

**Comment by jacques42** [comment]
A possible approach would be to key off the new admin panel setting for "collage only" in the remote button Server Script. If the setting is active then always emit a collage trigger event, also for short button press. Let me know what would look like help, and I'm happy to look into it. Should be fairly straight forward. 

One other thought and maybe you got it already covered - the admin panel should avoid conflicting parameters to be active at the same time. Here a conflict could be that collage is deactivated and at the same time only collage is allowed for an event. 

Best,
Jacques42
