### ISSUE TITLE
Collage - retake a single picture

### ISSUE THREAD

**Issue by lasolco** [andi34/photobooth#166]
Hi, I noticed during a collage a nice new feature.

For example, you do 4 pictures during the collage, but during the 2nd picture a mistake took place. So it would be great to have the possibility to retake the picture or to request the user to accept a picture for the collage.

I would like to suggest to add the possibility to request the user after each picture of the collage to acknowledge the picture or do a retake.

Thank you very much!

Best regards

**Comment by andi34** [comment]
Hey @lasolco !
Thanks for your suggestion. I am about to rework some code of the collage creation and will take a look on your idea once I've more time (there's some other stuff on my to-do-list too which I need to finish first).

For future feature request(s) please use the feature request template.

Best regards

Andi

**Comment by andi34** [comment]
Started working on it.

![ezgif-4-93153365c4ae](https://user-images.githubusercontent.com/6080900/107141155-422fc500-6927-11eb-8e2f-971eaa4c5c9d.gif)

Todo: 
- don't repeate picture
- delete old picture to take a new one

**Comment by andi34** [comment]
Will be included in next release

**Comment by jacques42** [comment]
Did you get to test if this also works with an active RemoteBuzzer integration ? Let me know in case not and I'll have a look

**Comment by andi34** [comment]
No, would be great if you're able to test. But I have to push one fix later.

**Comment by andi34** [comment]
![ezgif-4-cb1f11611c61](https://user-images.githubusercontent.com/6080900/107156401-61a60c80-697e-11eb-8923-dff7fd25480b.gif)
