### ISSUE TITLE
Print confirmation.

### ISSUE THREAD

**Issue by thymon13** [andi34/photobooth#20]
Hi,

Is it possible to confirm with pop up or other when I click on print button ?
Currently nothing happens on the screen when you click on it. And people by reflex click again several times over.

Sorry for my English :)

Thanks in advance.

thymon

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/issues/44

**Comment by flighter18** [comment]
I implemented the print confirmation with sweetalert2.all.min.js
https://sweetalert2.github.io/#examples

1. download sweetalert2.all.min.js and save it to folder "resources"
2. add sweetalert2 to head of index.html
`       <script type="text/javascript" href='resources/sweetalert2.all.min.js'> </script>
        <script type="text/javascript">
                function printConfirmation() {
                        swal({
                                type: 'success',
                                title: 'Druckauftrag gestartet',
                                showConfirmButton: false,
                                timer: 1600,
                                allowOutsideClick: false
                        })
                }
`
3. Add "onclick" Function to the printbutton in index.html
`onclick="printConfirmation()"`

4. Change the gallery print button in index.html
`'<?php if($config['use_print']){ echo '<a style="padding-top:14px"  href="#" onclick="printConfirmation();" class="gal-print" title="Close (Esc)"><i class="fa fa-print"></i> </a>'; }?>`

5. Change the z-index from swal2-container in resoureces/css/style.css
.swal2-container {
  z-index: 20000;
  -webkit-overflow-scrolling: auto
}

now the only problem i have is, if i push the print button on a mobile device in the gallery,  
on one hand, the confirmation appears but on the other hand the webpage zooms in.
My thinking is, the push on the print button simulates a double tap -> so the mobile device zooms in. 
Maybe the best solution is, to close the picture preview after the bush, on the print button. 
Has anybody a clue how to close a picture preview in the gallery? I couldn't get it.

[My problem](https://youtu.be/LfzfPWZhYK4)

**Comment by andi34** [comment]
I am quite busy this week, I'll take a look once I find time. I think there's an easier way, adding something like
```
setTimeout(function () {
    $('.loading').text('Printing... Please wait...');
}, 400);
clearTimeout(timeOut);
public.resetTimeOut();
```
Inside core.js at the printing function

**Comment by flighter18** [comment]
Thanks for your input.
I added my swal2 function inside core.js at the printing function and removed all onclick from the index.php. I also changed the gallrery printbutton to his defaults. 
It works perfect without any problem.

**Comment by andi34** [comment]
Could you paste the output of:
```
git diff resources/js/core.js
```

**Comment by flighter18** [comment]
this is core.js

```
+++ b/resources/js/core.js
@@ -164,7 +164,15 @@ var photoBooth = (function () {
             $.ajax({
                 url: 'print.php?filename=' + encodeURI(result.img),
             }).done(function (data) {
-            })
+                            swal({
+                        customClass: 'myPrintConfirmation',
+                        type: 'success',
+                        title: 'Druckauftrag gestartet',
+                        showConfirmButton: false,
+                        timer: 1600,
+                        allowOutsideClick: false
+                })
+           });
         });

         // Add Image to gallery and slider
@@ -371,7 +379,15 @@ var photoBooth = (function () {
         $.ajax({
             url: 'print.php?filename=' + encodeURI(img),
         }).done(function (data) {
-        })
+                        swal({
+                        customClass: 'myPrintConfirmation',
+                        type: 'success',
+                        title: 'Druckauftrag gestartet',
+                        showConfirmButton: false,
+                        timer: 1600,
+                        allowOutsideClick: false
+                })
+       });
     });

     // chroma keying print
```

**Comment by flighter18** [comment]
had to add the z-index to resources/css/style.css for the gallery confirmation

```
@@ -844,3 +844,10 @@ hr.small {
     bottom: auto;
   }
 }
+.swal2-container {
+  z-index: 20000;
+  -webkit-overflow-scrolling: auto
+}
+.myPrintConfirmation .swal2-icon {
+ border-color: orange;
+}
```

**Comment by flighter18** [comment]
finally i added the src to index.php

```
index 94fb420..43ade29
--- a/index.php
+++ b/index.php
@@ -10,6 +10,9 @@ require_once('folders.php');
 require_once('db.php');

 ?>
+<script src="resources/sweetalert2.all.min.js">
+}
+</script>
 <!DOCTYPE html>
 <html>
 <head>
```

**Comment by andi34** [comment]
Thanks. I'll check if my solution also works as it would need less dependencies and would make it easier to maintain.
If not I'll add your solution until I find a better one :)

**Comment by andi34** [comment]
@flighter18 i've added something to test on "dev" branch. I've no printer, could you please check if it works?

**Comment by flighter18** [comment]
I didn't get any confirmation.

git status:
` Author: Andreas Blaesius <andi@unlegacy-android.org>
Date:   Tue Aug 13 19:51:35 2019 +0200
admin: fix print message and command `

**Comment by andi34** [comment]
dev branch? Or master branch?

Mh... I'll reinvestigate

**Comment by flighter18** [comment]
on dev branch

**Comment by andi34** [comment]
Could you check again please, pushed another change

**Comment by flighter18** [comment]
still no message.

**Comment by andi34** [comment]
Thanks. I am only mobile now, will check on PC again and let you know if there's something more

**Comment by flighter18** [comment]
perfect

**Comment by andi34** [comment]
Not sure if it works now. Still only mobile and not near a PC the whole day.

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/443b15eecf6c35d422896c975ccead78f823b9cb

Maybe have to adjust the class & id and also add some changes to style.css for changed class & id

Edit:
Did I mention I hate GitHub mobile?
Sorry for close & reopen

**Comment by thymon13** [comment]
@andi34 @flighter18 thank you a lot for your interest !! 
I'm glad to see so much quick response

I can already read the French translation. You speak French ?

**Comment by flighter18** [comment]
@andi34 still no confirmation

**Comment by andi34** [comment]
@flighter18 danke fürs testen. Oh man... Muss wohl doch die Tage am PC dann schauen.

@thymon13 it is currently WIP and does not work how I've tried to implement it. Have to check next days when I am on a desktop PC (currently mobile only). I don't speak french, but from my Android development i know some people from different countries who can translate for me into french. Some basic translation via Google translate.

**Comment by andi34** [comment]
If I haven't forgotten anything this branch should work: https://github.com/andi34/photobooth/commits/printconfirm
Please note: you must have cloned from my GitHub:
```
git fetch origin
git checkout origin/printconfirm
```
I'd like to have a way implement in the end without depending on other projects to make maintaining easier in the end.

**Comment by andi34** [comment]
Removed WIP stuff out of dev branch as dev branch is used by default on my GitHub.
I'll work on it when I have more time again.

**Comment by thymon13** [comment]
hi,
I don't understood how I can test this branch ? I'm noob in GIT

**Comment by andi34** [comment]
If you've cloned from my git you can use the instructions 2 posts above yours.
```
cd /var/www/html
git fetch origin
git checkout origin/printconfirm
```

**Comment by andi34** [comment]
But stupid question:
Isn't it added already via
```
$config['print']['msg']
```
???

**Comment by thymon13** [comment]
@andi34 
> If you've cloned from my git you can use the instructions 2 posts above yours.
> 
> ```
> cd /var/www/html
> git fetch origin
> git checkout origin/printconfirm
> ```

Ok thx. I had to confirm the commit
But nothing happen when I click "print" like before...

> But stupid question:
Isn't it added already via
> 
> ```
> $config['print']['msg']
> ```
>???

Oh yes. But nothing... :)

**Comment by thymon13** [comment]
It works for you?

**Comment by thymon13** [comment]
I am sorry to up the topic. 
But it does not work at all. Nothing happens when I click on print. Did I miss something?

I am on the branch "confirmprint"

**Comment by andi34** [comment]
No printer to test here.
I'll update in Sunday, maybe you can test again

**Comment by thymon13** [comment]
@andi34 no printer needed for test it

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/a32e41ef1b9d6700353860f3ebe037c76a4f67b1

try again with that (branch updated)

**Comment by thymon13** [comment]
nothing :( like before.

**Comment by thymon13** [comment]
After another try: the print function does not work anymore with this branch

**Comment by andi34** [comment]
After latest Change?
I've removed them again and updated index.php as mentioned before by flighter18.
https://github.com/andi34/photobooth/commit/45c39e25e61c13883593ddf7d8b5fce1a8cad101

@flighter18 what am I missing here https://github.com/andi34/photobooth/commit/fdde9a0acac197b472b48f49ac635d7cf76428d7 ?

**Comment by flighter18** [comment]
@andi34
I am on holiday right now, will be back next week 😊
So can‘t check it. Sorry

**Comment by andi34** [comment]
No Problem.
Have nice holidays! I'll have some soon too finally 😅

**Comment by flighter18** [comment]
had some time :) 
did a new git clone from the new version and added the function again. Should now work.

also did a new merge request

**Comment by thymon13** [comment]
@flighter18 
I tested. Works well.
But on touch pad the display has a problem now
![IMG_0574](https://user-images.githubusercontent.com/18228022/64729614-c89b6980-d4dd-11e9-8c7a-b0caa77d2845.jpg)

**Comment by thymon13** [comment]
@flighter18 

Thank you !
Works when I take a picture.  But does not work from the gallery.

EDIT : 
When I click, the function is executed twice. 
In gallery print confirmation is launch behind the picture. So we do not see it

**Comment by thymon13** [comment]
@flighter18 

After other tests, I see that this generates bug page layout on the home page.
(sorry for my english)

**Comment by flighter18** [comment]
@thymon13 I have no problem on my test system. What for a browser do you use? 

And is the color of the hook orange at the end (see pic below) or does it stay green? 
![Bildschirmfoto 2019-09-13 um 21 52 38](https://user-images.githubusercontent.com/26125704/64890947-f6fd7e00-d670-11e9-995d-aa74e7ebc6eb.png)


Could you send a print screen from the bug page layout?

**Comment by thymon13** [comment]
@flighter18 
It does stay green, and it is executed twice.

https://youtu.be/qIaNuETD6eI

**Comment by flighter18** [comment]
@thymon13 

thank you for the video. 
Are those lines in your style.css file?
```
.swal2-container {
  z-index: 20000;
  -webkit-overflow-scrolling: auto
}
.myPrintConfirmation .swal2-icon {
 border-color: orange;
}
```

the first one makes the print cofirmation visible in the gallery (z-index). The second one changes the color.

**Comment by flighter18** [comment]
@thymon13 
btw.

After yesterday's use of the photobooth at a wedding, I will change the confirmation a little bit. 

My idea:
After pushing the print button the page will automatically leave "picture view" mode and return to the home page or gallery page + it will display the print confirm.

**Comment by flighter18** [comment]
@thymon13 

Check out my repo. I added this close function:

https://youtu.be/NTxXxTOfN8U

could you test it?

**Comment by thymon13** [comment]
@flighter18 
Private video...

**Comment by flighter18** [comment]
@thymon13

😝🙈
Please check it again

**Comment by thymon13** [comment]
@flighter18 
cool !
Yes I could test it...

**Comment by flighter18** [comment]
@thymon13 
i did a nother push.

now the print confirmation message comes from the language file.

**Comment by flighter18** [comment]
@thymon13 
be sure to remove your browser cache befor testing.
I had some trubels with my google chrome browser.

**Comment by thymon13** [comment]
> @thymon13
> now the print confirmation message comes from the language file.

@flighter18 
Clean !

**Comment by andi34** [comment]
@flighter18 could we try https://gist.github.com/andi34/48a5c4f5e21e02bd6921bf86ca8e1902 instead swal?
Less dependencies = less maintain time which makes it easier to update in future.
I'd try to adjust it with some of your changes later or tomorrow evening.

**Comment by andi34** [comment]
Pushed to my dev branch. Not tested and needs adjustment.
Will be one commit later, quickly done at work 🙈

Edit:
Updated, clean commits now.

**Comment by andi34** [comment]
Looks fine to me and like a clean solution.
https://github.com/andi34/photobooth/commit/3272cb7b96948d5aa9c6f6c353f392ddeebd87a2
https://github.com/andi34/photobooth/commit/bc3daf1c571124bf483b9b84dbb13b6a7a2a5de9

@flighter18 and @thymon13 could both of you please test?

**Ready for review**
- [ ] print confirmation ( @flighter18 , @msmedien ): 
  https://github.com/andi34/photobooth/commit/3272cb7b96948d5aa9c6f6c353f392ddeebd87a2
  https://github.com/andi34/photobooth/commit/bc3daf1c571124bf483b9b84dbb13b6a7a2a5de9

To test this changes:
Make sure your local clone does ignore filemode changes:
```
cd /var/www/html
git config core.fileMode false
sudo git config core.fileMode false
```
Now add my Github copy as remote and fetch the source:
```
git remote add andi34 https://github.com/andi34/photobooth
git fetch andi34
```
Make sure you have no local changes which will be lost, if you have you need to commit them. Best ist to keep them in a seperate branch you can go back to later:
```
git add --all
git commit -a -m "All my local changes"
git checkout -b myBackupBranch
```
Now switch to my source:
```
git checkout andi34/dev
```
Happy testing!

In case you need to switch back to your local source you only need to checkout to your backup branch which we've created before.
```
git checkout myBackupBranch
```

Questions? Let me know!

Please leave some feedback if the print confirmation works for you as expected. Quickly tested and seems to be fine.
Translation wrong/need adjustment? Let me know too before i merge the changes here!

**Comment by thymon13** [comment]
@andi34 
Ok I'll keep you informed

**Comment by andi34** [comment]
Found some nitpicks (see inline notes), will edit the commit one again in the evening

**Comment by flighter18** [comment]
@andi34 
I tested it. works like a charm :)
The nitpicks are just small things, so i think we have the sollution now!

**Comment by andi34** [comment]
Thanks for testing. Going to merge it into Andre's Source after work 
:)

**Comment by andi34** [comment]
Merged :) Thanks everyone :)
