### ISSUE TITLE
QR Code separat über Drucker/Bondrucker ausgeben & Bildausdruck Anzahl Einstellmöglichkeit

### ISSUE THREAD

**Issue by QuoterMusic** [andi34/photobooth#208]
**QR Code separat über Drucker/Bondrucker ausgeben**

Es wäre schön, wenn es die Möglichkeit gäbe, den QR Code nicht neben das Bild zu Drucken, sondern z.B. über einen Bondrucker separat auszugeben.

Format des Ausdruck was ich mir vorstellen würde wäre wenn machbar:
_Eventname
Bild
QR-Code
(Anpassbarer Text) für ggf. Passwort für Zugriffschutz_

So wäre es möglich die Bilder nach dem Event auf ein Webspace abzulegen und den Leuten die Möglichkeit zu geben auch nach der Veranstaltung die Bilder zu Downloaden. 

Falls sie es vor Ort vergessen haben oder der Andrang am Automaten zu groß war etc.

**Bildausdruck Anzahl Einstellmöglichkeit**

Als Zweites wäre es hilfreich, wenn man einstellen könnte vor dem Drucken wie viele Ausdrucke gemacht werden sollen.

Wenn mehrere Personen auf einem Bild sind, will wahrscheinlich jeder einen Ausdruck eine Auswahlmöglichkeit der Anzahl der zu druckenden Bilder wäre diesbezüglich sehr hilfreich um nicht jedes Bild einzeln ausdrucken zu müssen.

**Comment by Metropo** [comment]
Das überschneidet sich mit einigen Ideen, die ich in der nächsten Zeit umsetzen möchte.
Auf meiner Liste steht noch 
**Direkter Upload auf einen Webspace (z.B. über UMTS-Modem) und anpassung des QR codes.**
So muss sich keiner am Fotobox-Wlan anmelden
**Und beschränkung der ausgedruckten Bilder und Push-Benachrichtigung wenn das Fotopapier ausgeht.**
Damit man auch einen kleinen Canon-Selphi Drucker verweden kann, ohne dass alle 10 Minuten das Papier leergedruckt ist ;)

Wenn ich damit anfange, würde ich die von @QuoterMusic  genannten Wünsche mit einbauen. Aber ich kann leider keine Zeit nennen ;)
Beste Grüße

**Comment by andi34** [comment]
@Metropo vielen Dank!

**Comment by QuoterMusic** [comment]
@Metropo Vielen Dank

Genau so hätte ich mir das auch vorgestellt mit dem Upload.
Das mit den Push-Benachrichtigungen Klingt auch sehr Interessant.

Ich habe leider aktuell auch sehr wenig Zeit sonst hätte ich es selbst versucht umzusetzen, Es ist ja aber eh immer noch Corona daher hat es keine Eile freut mich sehr das du dich daran setzt. 👍 

Beste Grüße
