### ISSUE TITLE
feature: allow to change rgb value on Seriously.js via config

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#211]
**Is your feature request related to a problem? Please describe.**

Green screen might have a different green color, keying result depends on it.

**Describe the solution you'd like**

Allow to adjust the rgb value via config inside the Adminpanel.

**Describe alternatives you've considered**

**Additional context**

I'll take a look at once I have enough time. Making the values a config can be done quickly, slider for each value, range Config from 0-255, steps 1.

Maybe we can add a small preview of the green color?

**Comment by jacques42** [comment]
Closed via PR https://github.com/andi34/photobooth/pull/213
