### ISSUE TITLE
MERGED: frame around the picture

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#22]
Adjust and optimize source from Steffen Musch.

Need to know: Example boarder can be used without trouble? Source & license?

**Comment by Nie-Oh** [comment]
@andi34 

it is better you ceate a new Example Boarder. 

Steffen

**Comment by andi34** [comment]
frame.png needs to be added to root of photobooth.
https://github.com/andi34/photobooth/commit/20a9b16623431942aed1610e843ae6f2e665366b#diff-d5fde551bb3c77d93baa17a8ba21e781R58

If someone can share a frame which can be used in this project without license issues let me know.
No frame.png added by default until that.

**Comment by andi34** [comment]
![deb800943fb1e89d31da5c8bf0660267](https://user-images.githubusercontent.com/6080900/64485751-9ad7cb80-d224-11e9-878f-d47f83e1ccbc.jpg)

**Comment by andi34** [comment]
added example frame

![affa4b9397dfd454c3cd5939265cd154](https://user-images.githubusercontent.com/6080900/64486345-39b3f600-d22c-11e9-96e6-42a1e2704daa.jpg)

**Comment by andi34** [comment]
merged
