### ISSUE TITLE
Error french translate

### ISSUE THREAD

**Issue by thymon13** [andi34/photobooth#25]
Hi !

On the line number 7 in "fr.js"

`7	"takeCollage": "Prendre une colloage!",`
the 2nd letter "O" is to be removed. And In French we say: "UN collage" not "UNE collage"

"Photos Montage" is a suitable term for "collage" translation

**Comment by andi34** [comment]
Could you add a inline note here please with the complete line translation?
https://github.com/andi34/photobooth/commit/c436d6b010319f2aba58ca0cd635b35edf59302f

I've to correct some other lines too as you can see from my inline notes

**Comment by thymon13** [comment]
Done ! As well as other changes in translation

**Comment by flighter18** [comment]
@thymon13 thank you! :)
