### ISSUE TITLE
Bug: standalone gallery freeze while closing picture

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#252]
Open standalone gallery. Click on a thumbnail to see the full-size image. Close the image.
Gallery freezes.

Problem is inside the `photoinit.js`:
```
        gallery.listen('destroy', function () {
            rotaryController.focusSet('#gallery');
        });
```

Rotary controller is not added to standalone gallery yet.
Rotary Controller should be disabled in standalone gallery or only be used on standalone gallery if enabled.

**Comment by jacques42** [comment]
PR https://github.com/andi34/photobooth/pull/253 fixes the crash and fully implements rotary button support - can some pls try it out ?
