### ISSUE TITLE
Hide all buttons

### ISSUE THREAD

**Issue by h4ns123** [andi34/photobooth#255]
In case hardware buzzers are used without a touch screen, it would be nice to be able to hide all buttons in the preview as well (I haven't found a way to hide the "filter-button" and the "home-button")

**Comment by jacques42** [comment]
Use this switch to turn off filters, the button will be hidden and not visible. 

![grafik](https://user-images.githubusercontent.com/37227800/121589664-a37fb600-ca37-11eb-9128-384652369cd6.png)

Indeed the home button currently can't be hidden. I'll look into it when I find some time

**Comment by jacques42** [comment]
PR https://github.com/andi34/photobooth/pull/256 adds a config switch to hide the home button on the results screen.
