### ISSUE TITLE
Unexpected return to start page

### ISSUE THREAD

**Issue by h4ns123** [andi34/photobooth#272]
It happened to me a few times that no image was triggered after the countdown and the view went straight to the start page. I noticed that this happened more often when I reduced the duration of the result page to 10 seconds and started a new countdown after a few seconds.

Is it possible that the command to return to the start page persists even after starting a new countdown and prevents the camera from triggering?

**Comment by andi34** [comment]
Please test https://github.com/andi34/photobooth/pull/273

**Comment by h4ns123** [comment]
Hi Andi!
The camera always triggers now! Thanks! However, the view still switches to the home page right after and the new photo is not displayed...

**Comment by andi34** [comment]
Use a longer time to return to the start page :)

**Comment by jacques42** [comment]
Thanks for adding my suggestions into PR#273. I did some extensive testing and where I was able to reprocue the bug, now this PR seems fixes it. 

@h4ns123 can you please also test this PR #273 and see if this fixes the bug for you ?
