### ISSUE TITLE
Raspberry Pi as Access Point

### ISSUE THREAD

**Issue by Fabian2305** [andi34/photobooth#276]
Hey,
first of all thank you very much for sharing the project.
Is it possible to use the Raspberry also as an access point to show the web interface on an Ipad e.g. without using any other networks.

PS: im new in Raspberry, so an instruction how to do it would be great.

Thank you very much

**Comment by andi34** [comment]
Hey!
Instructions can be found inside the FAQ of our Wiki:
https://github.com/andi34/photobooth/wiki/FAQ#turn-photobooth-into-a-wifi-hotspot

**Comment by Fabian2305** [comment]
Hey, I tryed like the instruction says, but it doesn't work.
I only get "sudo: ./setup-network.sh: command not found"
What did I do wrong?
Thank you

**Comment by andi34** [comment]
What version of Photobooth you've installed?
Sure you're trying to run the command inside the right path (/var/www/html/vendor/rpihotspot) ?

**Comment by Fabian2305** [comment]
I've installed Option 2, ist Version 3.1.0
Yes I used the right path and checked it a few times, also after reboot

Andreas Blaesius ***@***.***> schrieb am Di., 27. Juli 2021,
12:31:

**Comment by andi34** [comment]
Does the file exist?
Maybe try
`sudo bash setup-network.sh  --install-upgrade --ap-ssid="Photobooth" --ap-password="password" --ap-password-encrypt
--ap-country-code="CA" --ap-ip-address="10.10.10.10" --wifi-interface="wlan0"`

**Comment by andi34** [comment]
There's the script, you can also execute it from Desktop for example
https://raw.githubusercontent.com/andi34/rpihotspot/master/setup-network.sh

**Comment by Fabian2305** [comment]
I've tryed all your tips, but it still doesn't work and its the same error
message.
First I tested "sudo bash setup-network.sh" and the raspi answered a long
list of code examples. I tryed them all, but without success.
So I used "wget
https://raw.githubusercontent.com/andi34/rpihotspot/master/setup-network.sh"
but it says "Permission denied".
And even after reboot the error "sudo: ./setup-network.sh: command not
found" stays the same!

Andreas Blaesius ***@***.***> schrieb am Di., 27. Juli 2021,
16:21:

**Comment by andi34** [comment]
https://thepi.io/how-to-use-your-raspberry-pi-as-a-wireless-access-point/

**Comment by Fabian2305** [comment]
I've tryed this instruction yesterday, but without any success. Everytime I
tryed to connect a device, my mibilephone or computer says: "no IP-Adress
available" and the connection failed.

Andreas Blaesius ***@***.***> schrieb am Di., 27. Juli 2021,
22:05:

**Comment by andi34** [comment]
Maybe you start from scratch with a clean raspberry pi os installation?

**Comment by Fabian2305** [comment]
I've already tryed this a few times after I tested many different instructions on the internet. I deleted the sd card and installed everything from the beginning.

> Am 27.07.2021 um 23:10 schrieb Andreas Blaesius ***@***.***>:
> 
> Maybe you start from scratch with a clean raspberry pi is installation?

**Comment by APLtres** [comment]
Hi, for me worked when I executed this command:

    sudo chmod ug+x ./setup-network.sh

before this comment:

    sudo ./setup-network.sh --install-upgrade --ap-ssid="Photobooth" --ap-password="password" --ap-password-encrypt --ap-country-code="CA" --ap-ip-address="10.10.10.10" --wifi-interface="wlan0"
