### ISSUE TITLE
[FEATURE]: Enable HID keyboards as hardware buttons

### ISSUE THREAD

**Issue by jacques42** [andi34/photobooth#284]
**Is your feature request related to a problem? Please describe.**

1) Using the keyboard to trigger a picture / collage, the screen needs to be locally connected to the server system. In scenario's where the screen is i.e. connected through WLAN, to trigger via keyboard does not work. 

2) Many USB devices register as generic HID keyboard to the operating system. 
 
**Describe the solution you'd like**

Enable the use of a HID keyboard devices to trigger pictures / collage. Also support WLAN connected screens. 

**Describe alternatives you've considered**

**Additional context**

**Comment by andi34** [comment]
Reopen as my changes don't work if Photobooth isn't opened in a browser.

**Comment by andi34** [comment]
Keep open
