### ISSUE TITLE
Hardware button option does not exists in admin panel

### ISSUE THREAD

**Issue by MasterJochen** [andi34/photobooth#287]
Remote Buzzer Hardware Button feature in the admin GUI 

well that does simply not exist or is wierdly hidden also my version is 2.1.0-alpha but under new it shows 2.1.0 so i tryed to update as explained here but that only showed me newest version allready installed. and one more thing in the FAQ it says install this script for hardware button but on a other page it says its not nessesary any more in the new version . im confused. btw grate program and thanks for reading :D

**Comment by andi34** [comment]
Hey!
Have you installed from my git repo or from Andrés git repo? Sounds to me like you've not installed from my git repo.

A lot of changes have been made on v3. A clean installation is recommend!
Follow the steps mentioned here:
https://github.com/andi34/photobooth/wiki/Installation-on-Debian

After installation an up-to-date FAQ can be found via 
http://localhost/faq and matches your installed Photobooth version.

I'd recommend to choose "latest development version" if asked.

If you like to update by hand anyway:
https://github.com/andi34/photobooth/wiki/Update-Photobooth

If you have further questions please join our telegram community :)
https://t.me/PhotoboothGroup
