### ISSUE TITLE
[FEATURE]: Collage with static picture

### ISSUE THREAD

**Issue by joschre** [andi34/photobooth#289]
**Describe the solution you'd like**
The photo box only takes 3 pictures and the 4th is static. E.g. a picture of the bride and groom or the birthday child.
The 4th picture can be selected via the admin panel.

![IMG_20210807_001743](https://user-images.githubusercontent.com/5621303/128576367-85c43e97-5821-451e-af15-bc228c973860.jpg)

**Comment by andi34** [comment]
Thanks for the idea, it's something I can look at when I have more time.

**Comment by lagrandeours** [comment]
hello  
joschre why just adding le "4th" pict in your frame ?

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/pull/436

Feature was added
