### ISSUE TITLE
Change GPIO for hardware button

### ISSUE THREAD

**Issue by serpentes80** [andi34/photobooth#297]
hi there,

is it possible to change the default hardware button GPIOs?
didn'f find any config for this yet.

Greetings

**Comment by andi34** [comment]
Not through the Adminpanel because it needs adjustments inside the /boot/config.txt if you make changes to them.
But feel free to adjust them your needs here;
https://github.com/andi34/photobooth/blob/2fbdac3fdbb29d8f1a6cd466ab6b02946c72febe/config/config.inc.php#L233-L252
