### ISSUE TITLE
[BUG]: Collage Hardware Button

### ISSUE THREAD

**Issue by Magicdaniel** [andi34/photobooth#300]
Hi, i think i found a bug with the hardware Button for the Collage.

I have two hardware buttons. One for the Picture mode and one for the Collage mode.
If i press the collage button, the first picture will be taken. Because i disabled the automatic mode i have to press again for the second picture, but nothing happens.
At the debug panel this message will pop up: 
buttonActiveCheck error state - requested GPIO 20 , for value 0 but buttonIsPressed: 20

If i can help with screenshots or made something wrong. Tell me pls :)

**Comment by andi34** [comment]
From a different conversation:

> I got this error: Remote Buzzer Server [1020]: buttonActiveCheck error state - requested GPIO 21 , for value 0 but buttonIsPressed: 21
> Got it, with an pull-up resistor to 3.3V it works fine. Sorry.
>

**Comment by jacques42** [comment]
yes, I can confirm this does not work in the code. Some substantial misses, and needs some work to fix it. I am working this in branch  [bugfix/remotebuzzer-collagebutton](https://github.com/andi34/photobooth/tree/bugfix/remotebuzzer-collagebutton)

**Comment by jacques42** [comment]
Will be fixed by PR# https://github.com/andi34/photobooth/pull/351
