### ISSUE TITLE
USB Sync funktioniert nicht

### ISSUE THREAD

**Issue by serpentes80** [andi34/photobooth#306]
Hallo

der USB Sync der Fotos läuft bei mir nicht.

habe den Stick nun auch schon "extra" als "PHOTOBOOTH" formatiert und so im Admin Backend eingetragen...
im Log erscheint immer nur:

[ 2021-09-01T13:38:05.251Z ]:  Sync-To-Drive server [996]: USB target  P H O T O B O O T H
[ 2021-09-01T13:38:05.262Z ]:  Sync-To-Drive server [996]: PID file created [data/tmp/synctodrive_server.pid]
[ 2021-09-01T13:38:05.264Z ]:  Sync-To-Drive server [996]: Starting server process
[ 2021-09-01T13:38:05.264Z ]:  Sync-To-Drive server [996]: Interval is [10] seconds
[ 2021-09-01T13:38:15.278Z ]:  Sync-To-Drive server [996]: Checking for USB drive
[ 2021-09-01T13:38:15.351Z ]:  Sync-To-Drive server [996]: Processing drive PHOTOBOOTH -> /dev/sda1
Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address (polkit-error-quark, 0)
Error mounting /dev/sda1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not authorized to perform operation
[ 2021-09-01T13:38:15.426Z ]:  Sync-To-Drive server [996]: Mounted drive sda1 -> 
[ 2021-09-01T13:38:15.427Z ]:  Sync-To-Drive server [996]: Starting sync to USB drive ...
[ 2021-09-01T13:38:15.427Z ]:  Sync-To-Drive server [996]: Source data folder [/var/www/html/data]
[ 2021-09-01T13:38:15.428Z ]:  Sync-To-Drive server [996]: Syncing to drive [/dev/sda1] -> []
[ 2021-09-01T13:38:15.429Z ]:  Sync-To-Drive server [996]: Executing command: < rsync -a --delete-before -b --backup-dir=deleted --ignore-existing --include='*.jpg' --include='*/' --exclude='*' --prune-empty-dirs /var/www/html/data photobooth-pic-sync >
[ 2021-09-01T13:38:15.436Z ]:  Sync-To-Drive server [996]: Rsync child process PID: 1174 started
[ 2021-09-01T13:38:15.759Z ]:  Sync-To-Drive server [996]: Rsync child process PID: 1174 finished after 322 ms
[ 2021-09-01T13:38:15.759Z ]:  Sync-To-Drive server [996]: ... finished sync, going back to sleep
[ 2021-09-01T13:38:25.287Z ]:  Sync-To-Drive server [996]: Checking for USB drive
[ 2021-09-01T13:38:25.345Z ]:  Sync-To-Drive server [996]: Processing drive PHOTOBOOTH -> /dev/sda1
[ 2021-09-01T13:38:25.345Z ]:  Sync-To-Drive server [996]: Mounted drive sda1 -> /media/pi/PHOTOBOOTH
[ 2021-09-01T13:38:25.345Z ]:  Sync-To-Drive server [996]: Starting sync to USB drive ...
[ 2021-09-01T13:38:25.345Z ]:  Sync-To-Drive server [996]: Source data folder [/var/www/html/data]
[ 2021-09-01T13:38:25.345Z ]:  Sync-To-Drive server [996]: Syncing to drive [/dev/sda1] -> [/media/pi/PHOTOBOOTH]
[ 2021-09-01T13:38:25.346Z ]:  Sync-To-Drive server [996]: Executing command: < rsync -a --delete-before -b --backup-dir=/media/pi/PHOTOBOOTH/deleted --ignore-existing --include='*.jpg' --include='*/' --exclude='*' --prune-empty-dirs /var/www/html/data /media/pi/PHOTOBOOTH/photobooth-pic-sync >
[ 2021-09-01T13:38:25.350Z ]:  Sync-To-Drive server [996]: Rsync child process PID: 1281 started
[ 2021-09-01T13:38:25.359Z ]:  Sync-To-Drive server [996]: Rsync child process PID: 1281 finished after 8 ms
[ 2021-09-01T13:38:25.359Z ]:  Sync-To-Drive server [996]: ... finished sync, going back to sleep

nur werden keine Fotos auf den Stick kopiert.

**Comment by jacques42** [comment]
Did you say _yes_ when running the _install-raspian.sh_ Script during the installation of Photobooth ? In case not pls try

```
wget https://gist.githubusercontent.com/andi34/04c8607f5dacd6a0cebe2fda3674bf09/raw/0f4b54422d3324109c8daf18c6cf9184da63cfcf/enable-sync.sh

sudo bash enable-sync.sh
```
To fix it

**Comment by serpentes80** [comment]
danke :)
