### ISSUE TITLE
[FEATURE]: Resize and positioning from single photos

### ISSUE THREAD

**Issue by msmedien** [andi34/photobooth#310]
**Is your feature request related to a problem? Please describe.**
I want to use more specific frames for single shot photos. A bit smaller and rotated for a few degrees. Like in the attached example. But i cant find any options for this. Right now i'm only able to use fullsize photos and rotate them.

**Describe the solution you'd like**
The best solution would be some options for the photosize and position in the admin panel. Link shrink: XX%, left-margin: XX%, top-margin: XX% (or in px)

**Describe alternatives you've considered**
As alternativ i could think about some premade templates. (Like the collage option with 2x2, 1+3 and so one.) For example: left-top, left-right, centered, left-bottom, right-bottom.

**Additional context**
Screenshot of a small example.

![Vorlage_FotoBox_AMS_09_2021-Einzel](https://user-images.githubusercontent.com/55385728/133313394-408c2b04-f58b-4134-b46c-31d26e6b4448.jpg)

**Comment by tdonhauser** [comment]
This feature would be great! Also for collage configuration.

**Comment by andi34** [comment]
Currently I am busy in real life. If someone has time to add this feature I am going to review it. A PR is welcome.
