### ISSUE TITLE
Add config option for font size

### ISSUE THREAD

**Issue by mhellmeier** [andi34/photobooth#314]
**Is your feature request related to a problem? Please describe.**
The font is very hard to read on high-resolution screens. This mainly includes buttons like "Take picture", "Gallery" etc. or the text under the QR-code.

**Describe the solution you'd like**

Would be nice to add a config option to change the overall font size.

**Comment by andi34** [comment]
There's already an option inside the User-Interface section called `Default font size`.

For everything else you could add a own theme or using `private/overrides.css` to make small adjustments.
