### ISSUE TITLE
Wrong "Skip welcome screen" description

### ISSUE THREAD

**Issue by mhellmeier** [andi34/photobooth#319]
**Is your feature request related to a problem? Please describe.**

If I create a new build of the project, the _Welcome to your own Photobooth_ screen always appears at the first time. That's pretty annoying.

**Describe the solution you'd like**

Would be nice to get a possibility to disable this screen (e.g. a config option: "Always disabled welcome screen").

**Additional information**
I know about the following option but it's contradicting itself. On the one hand I would suggest that the welcome screen will be skipped if the "skip welcome screen" option is activated. On the other hand, the information text says "If enabled, a welcome screen is visible [...]".

![welcome-screen-option](https://user-images.githubusercontent.com/1036284/134768193-afb2ae71-53ca-4a38-bbe0-100429b78a38.png)

**Comment by andi34** [comment]
Description must be renamed, thanks for the finding!
No need for PR. Going to fix it in the evening.

**Comment by andi34** [comment]
Marked as **bug** instead **enhancement** as only the description is wrong. Option to skip the welcome screen already exists.

Personal configuration will always be used on update, if you enable the skip option it won't be visible again until you delete your personal config.
