### ISSUE TITLE
Put "Event" Option to Basic Config View

### ISSUE THREAD

**Issue by mhellmeier** [andi34/photobooth#320]
**Is your feature request related to a problem? Please describe.**

In the "Basic View" of the admin panel, I can change the Text left/right and the symbol of the front page. But I am not able to show this text on the front page (this is done by the "Event" switch which isn't displayed).

**Describe the solution you'd like**

Currently, I have to change the admin view from "Basic View" to "Expert View". Afterward, I am able to see the "Event" switch.

It would be nice if the "Event" switch can be transferred from the "Expert View" to the "Basic View".

**Comment by andi34** [comment]
No need for PR. Going to fix it in the evening.
