### ISSUE TITLE
Wiki Change: Remove flag from chrome kiosk mode option

### ISSUE THREAD

**Issue by mhellmeier** [andi34/photobooth#321]
**Describe the bug**

The wiki suggests to use the following option to start chrome in fullscreen mode:
```
@chromium-browser --noerrdialogs --disable-infobars --disable-translate --no-first-run --check-for-update-interval=31536000 --use-fake-ui-for-media-stream --start-fullscreen --kiosk http://127.0.0.1 --incognito --touch-events=enabled
```

If the device preview from gphoto2 is enabled, the browser asks for camera (webcam) permission on every reboot.  

**Expected behavior**

Don't show the chrome popup to give the permission every time.

**Environment (please complete the following information):**
 - OS: Pi OS
 - Browser: Chrome
 - Version: Latest dev branch

**Solution**
Remove the `--incognito` flag. This will store the "camera is allowed" option in the chrome settings and doesn't ask for it after every reboot.

**Comment by andi34** [comment]
FAQ can be updated via PR, changes inside the `dev` or `wiki` branch.
No need for PR. Going to fix it in the evening.
