### ISSUE TITLE
[BUG]: Gphoto2 preview not working with power save mode

### ISSUE THREAD

**Issue by smoki3** [andi34/photobooth#407]
### Describe the bug

Hi,

I tried to enable the preview mode during the countdown. But it is not working for me.

I using chromium 88 and a Nikon D610. 

If I enable the power saving mode for the preview I dont get any image during the countdown. But the camera is opening the shutter as soon I press the release button.

If I disable the power saving mode then the preview is always shown and everthing is working as expected. 

I did a clean install with the latest dev branch and lastest raspbian OS. 

### Steps to reproduce the behavior

If I enable the power saving mode for the preview I dont get any image during the countdown. But the camera is opening the shutter as soon I press the release button.

If I disable the power saving mode then the preview is always shown and everthing is working as expected. 

### Expected behavior

The preview is shown as soon I press the release button.

### Photobooth Version

latest dev

### Browser and browser version

Chromium 88

### Operating System

Raspberry OS

### Did it work before?

No

### Latest working version

-

**Comment by andi34** [comment]
Have you tried python gohoto?
https://github.com/andi34/photobooth/blob/dev/faq/faq.md#how-to-get-better-performance-using-gphoto2-as-preview

This doesn't sound like a general Photobooth issue.
On a mobile phone I had an issue in the past with chrome not updating the preview from device cam until I moved chrome into the background and taking it in the foreground again.

**Comment by up-87** [comment]
How long is your countdown? If you disable power saver mode it'll take several seconds until the camera preview is ready. Same would be true if you were using the python script with power saver mode active in the script. Your camera will only be able to show the preview instantly if you disable power saver mode. Without it it can take 2 to 5 seconds until the preview is ready. Maybe even more. Try a really long countdown. My assumption would be that the camera preview will get available.

**Comment by DIY89** [comment]
Maybe your fault is related to a small bug in the `core.js`
`api.startCountdown = function (start, element, cb) {`
`        let count = 0;`
`        let current = start;`
`        const stop = start > config.preview.stop_time, 10 ? start - config.preview.stop_time, 10 : start;`

add 
`parseInt()` to stop time  `const stop = start > parseInt(config.preview.stop_time, 10) ? start - parseInt(config.preview.stop_time, 10) : start;`

**Comment by er9xuser** [comment]
I did try to use python3 cameracontrol.py for livepreview...but unfortunately doesn't work. I'm using Canon EOS 1200D. And for manual in wiki. I'm not sure where to edit commands. Where to put python3 cameracontrol.py? I know where to put python3 cameracontrol.py --set-config capturetarget=1 but in the end...photobooth says something wrong.

**Comment by andi34** [comment]
> I did try to use python3 cameracontrol.py for livepreview...but unfortunately doesn't work. I'm using Canon EOS 1200D. And for manual in wiki. I'm not sure where to edit commands. Where to put python3 cameracontrol.py? I know where to put python3 cameracontrol.py --set-config capturetarget=1 but in the end...photobooth says something wrong.

it's a feature added to latest development branch. You need to install some packages and adjust the take picture command etc.
If you're having trouble on the setup feel free to join our telegram group because only photobooth issues can be discussed here on github.

**Comment by er9xuser** [comment]
What is Telegram group called?

**Comment by andi34** [comment]
Linked inside the README ;)
https://t.me/PhotoboothGroup

**Comment by er9xuser** [comment]
I'll try latest development branch. Thanks

**Comment by er9xuser** [comment]
Live preview works. But when capturing image...i get error:

[error] => File was not created
    [cmd] => python3 cameracontrol.py -s capturetarget=1 -c capture-image-and-download 2>&1
    [returnValue] => 0
    [output] => Array
        (
            [0] => Sending message: {'device': '/dev/video0', 'config': ['capturetarget=1'], 'imgpath': 'capture-image-and-download', 'bsm': False, 'chroma_image': None, 'chroma_color': None, 'chroma_sensitivity': None, 'chroma_blend': None, 'exit': False}
            [1] => Image captured
        )

    [php] => takePic.php


My take picture command is: python3 cameracontrol.py -s capturetarget=1 -c capture-image-and-download

**Comment by andi34** [comment]
You've at least forgot the `%s` (which is the path and filename for the image)

Try

`python3 cameracontrol.py -s capturetarget=1 -c capture-image-and-download %s`

**Comment by er9xuser** [comment]
Just for info. This command works: 

python3 cameracontrol.py -s capturetarget=1 -c capture-image-and-download -c %s
