### ISSUE TITLE
[FEATURE]: Photo Preview and Gallery with QR Code at the side

### ISSUE THREAD

**Issue by crazylenni** [andi34/photobooth#411]
### Is your feature request related to a problem?

No

### Description

Hi,

I would like to automate the photobooth as much as possible and want to minimise user input.
It would be nice if the QR code will not be showing up on demand, but as a standard on the left/right side of the gallery or photo preview (after a picture / collage was taken).

### Describe the solution you'd like

Show the QR code beside the visible picture

### Describe alternatives you've considered

I have a monitor without touchscreen (because I want to use gphoto2 live preview). There it is not usable to click the QR-code button with a mouse.

**Comment by CWempe** [comment]
I totally agree.

It would be great if the last QR-Code (and optionally its photo) would be show in the start page for X amount of time or until the next photo has been taken.
