### ISSUE TITLE
[BUG]: Touchscreen Buttons not working

### ISSUE THREAD

**Issue by mgineer85** [andi34/photobooth#427]
### Describe the bug

RPI4 bullseye, latest release version and last dev version tested, 7inch touchscreen connected via HDMI+USB

The webinterface seems not to accept any touch events from my touchscreen connecte to RPI.

Can anybody confirm this issue?

### Steps to reproduce the behavior

Open chromium
Go to localhost, photobooth opens
Try to click take picture button - doesn't do anything.
Click the button with mouse curser is working fine.

### Expected behavior

take a picture

### Photobooth Version

last stable and last dev version tested

### Browser and browser version

chromium latest bullseye version

### Operating System

RPI os Bullseye

### Did it work before?

No

### Latest working version

? not sure whether it worked in this fork any time - in last 2.10 release it worked.

**Comment by andi34** [comment]
Hey and thanks for your bug report. Touch issues aren't related to Photobooth, this must be either an OS / driver issue  or an Browser issue.


If touch is working on other parts of the OS you'll have to play around with chromium:
1. If you're starting chromium, make sure touch is enabled.
You can start chromium from terminal via command line:
`chromium-browser --touch-events=enabled`
I know that some user had issues with touch in the first start of chromium, maybe close it once and try again.

2. If still trouble with chromium, please try to downgrade to v88
https://github.com/Botspot/pi-apps

**Comment by mgineer85** [comment]
Hi @andi34 , thx for reply.
Indeed in the meantime I found it's not photobooth.
On my setup nowadays the touchscreen either is defective or wrong configured as there is a gap at exactly the positions where the action buttons are located.

Sorry for bothering you.
