### ISSUE TITLE
[LOCALIZATION]: Norwegian

### ISSUE THREAD

**Issue by madanielsen** [andi34/photobooth#437]
### Request a language

Would be great if Norwegian could be added

**Comment by andi34** [comment]
https://crowdin.com/project/photobooth/no

**Comment by andi34** [comment]
Norwegian will be added to the select menu in Adminpanel once 80% of translation are added on crowdin.

**Comment by andi34** [comment]
Hey again!

I am closing this localisation request as there's not much activity on crowdin. I am watching crowdin for changes frequently and going to add Norwegian to Photobooth once the translation status meets the requirements.

Thanks for your contribution!

Best regards

Andi
