### ISSUE TITLE
[FEATURE]: Collage Background

### ISSUE THREAD

**Issue by Nie-Oh** [andi34/photobooth#445]
### Is your feature request related to a problem?

No

### Description

a background picture would be nice in collage. 

### Describe the solution you'd like

a new variable in the admin panel. to declare the background picture. like the frames and so on....

### Describe alternatives you've considered

no idea

### Additional context

steffen

**Comment by andi34** [comment]
Hey and good morning!
The feature was removed in favor of the new frame handling. A proper frame allows to place parts of "the background" also in front of the single images.

To create a proper frame you should take one collage and use it inside gimp, Photoshop or any other software as background to add the placeholder for the single images.

**Comment by Nie-Oh** [comment]
Thank you andi34,

great idea!

**Comment by andi34** [comment]
You're welcome. If there's a good reason a background is needed instead using a frame let me know and I'll consider adding it back.

**Comment by DIY89** [comment]
I would like to have the background picture option for the collage because you otherwise will have a lot of white space with frames. Especially for the layout `1+3` or `3+1`. For the other layout frames are a better solution instead of background in my oppinion.

**Comment by andi34** [comment]
White spaces only happen if the resolution and the placeholder don't match in your frame and should be adjusted there. The placeholder also change depending on defined dpi for collage.
