### ISSUE TITLE
Ability to choose a frame before taking a picture

### ISSUE THREAD

**Issue by md-20** [andi34/photobooth#45]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
I love your software! It has so much functionality and is blazing fast with my Raspi4!
I only miss one thing: **the abiility to choose a frame before taking a picture**. I could imagine very funny frames, but they need to be seen before the image is taken to take the right props e..g.  That solution would need a selection button on first screen and then a window popping out giving the oppourtunity to select a frame, maybe between two or three frames you can tap or klick on.

**Comment by andi34** [comment]
it's currently not on my to-do list, but I'll keep the issue here open for development in future or in case some else likes to implement and send a Pullrequest.
