### ISSUE TITLE
[BUG]: Mistake in the German translation

### ISSUE THREAD

**Issue by webwurm** [andi34/photobooth#451]
### Describe the bug

On the admin-panel, the translation for "pre_photo_cmd" and "post_photo_cmd" are mixed up. The description is okay thow.

### Steps to reproduce the behavior

Set the language to German.

### Expected behavior

The translations are mixed up.

### Photobooth Version

current

### Did it work before?

No

**Comment by andi34** [comment]
https://crowdin.com/project/photobooth/invite?d=a5a5q41585e58373d5b3a393a383b3

**Comment by andi34** [comment]
Fixed already in latest dev branch since April 

https://github.com/andi34/photobooth/commit/1d4c2a9a5e6c2b084806a28968dff3fa086770c0

**Comment by andi34** [comment]
**Update Photobooth to latest development version via Terminal:**
```
sudo -u www-data -s
cd /var/www/html
git fetch origin
git checkout origin/dev
git submodule update --init
yarn install
yarn build
exit
```

**Comment by webwurm** [comment]
Thanks a lot!
