### ISSUE TITLE
[BUG]: E-Mail sending 

### ISSUE THREAD

**Issue by talentlos** [andi34/photobooth#453]
### Describe the bug

When sending a picture via email, the spinning loader icon does not disappear or change state, when email is sent. Because of the small and light green success message, users tend to press the button again and again not understanding, that the email has been sent.

### Steps to reproduce the behavior

send a picture via email in the gallery

### Expected behavior

"Spinning wheel" loader icon should stop and maybe button should change state in "done" and/or overlay should close by pressing button. maybe the success message should be bigger or color customizable for better visibility?

### Photobooth Version

latest

### Browser and browser version

all browsers

### Operating System

testet on OSX and Win11

### Did it work before?

No

**Comment by Nie-Oh** [comment]
I have the same Problem on Android

**Comment by andi34** [comment]
Hey and thanks for the report. I'll take a look at it later this week.
