### ISSUE TITLE
Implement fullscreen button for android tablets

### ISSUE THREAD

**Issue by md-20** [andi34/photobooth#46]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
On my android tablet status bar and tabs are shown when i open the photobooth-page in Chrome. I cannot open fullscreen mode.
But when I implement following simple code in index.php it works, maybe you could implement it as an option?:
`<button id="goFS">Go fullscreen</button>
<script>
  var goFS = document.getElementById("goFS");
  goFS.addEventListener("click", function() {
      document.body.requestFullscreen();
  }, false);
</script>
`
Source: [https://developers.google.com/web/fundamentals/native-hardware/fullscreen](url)
Thank you for your amazing work with this photobooth!

**Comment by andi34** [comment]
I'll take a look at it next days :)

**Comment by andi34** [comment]
Good idea where to place the button?

![Screenshot_20200406-125452](https://user-images.githubusercontent.com/6080900/78551398-f0e60f00-7805-11ea-86e9-dcff984abec5.jpg)

![Screenshot_20200406-125456](https://user-images.githubusercontent.com/6080900/78551406-f4799600-7805-11ea-81dc-ed6901f73dfa.jpg)

**Comment by andi34** [comment]
![Screenshot_2020-04-06_13-25-00](https://user-images.githubusercontent.com/6080900/78553737-0b21ec00-780a-11ea-94aa-b20e41a432b1.png)

i think it's looking quite ok now.

what do you think?

**Comment by md-20** [comment]
Yes it looks awesome. Will it Look in landscape mode similiar?

**Comment by andi34** [comment]
Depends on your display size, on 6 inch:

**Landscape**
![Screenshot_20200406-160013](https://user-images.githubusercontent.com/6080900/78566673-e173bf80-781f-11ea-878d-433cc4620421.jpg)

![Screenshot_20200406-160016](https://user-images.githubusercontent.com/6080900/78566692-e6387380-781f-11ea-842d-fcae33d94f81.jpg)

**Portrait**
![Screenshot_20200406-160030](https://user-images.githubusercontent.com/6080900/78566722-f18b9f00-781f-11ea-9b24-837cd6d0ba6c.jpg)

![Screenshot_20200406-160025](https://user-images.githubusercontent.com/6080900/78566746-f7818000-781f-11ea-8f36-39ccca2b4a8d.jpg)

**Comment by md-20** [comment]
Awesome, you rock! Do you implement it in options to enable and disable for those who want do decide if they need that option?

Oh and i wonder if the button could disappear when already in fullscreen? Maybe its not easy to implement?
 I think i can switch to normal mode by hitting the back button. But then it must reappear when going back to normal mode. 
No, i think the button can stay there :) So, if i want the button to disappear i can disable the option in admin panel when already in fullscreen, that should do it!

Thank you!

**Comment by andi34** [comment]
It's easy to hide it if you are in fullscreen, but if you exit fullscreen without reloading the page the button would still be gone.

**Comment by andi34** [comment]
```
diff --git a/resources/js/core.js b/resources/js/core.js
index 88e0233..c3b6021 100644
--- a/resources/js/core.js
+++ b/resources/js/core.js
@@ -653,6 +653,7 @@ const photoBooth = (function () {
         e.preventDefault();
         if (!document.fullscreenElement) {
             document.body.requestFullscreen();
+            $('#fs-button').hide();
         } else if (document.fullscreenElement) {
             document.exitFullscreen();
         }
```

**Comment by andi34** [comment]
Ready to use build:
[photobooth-SNAPSHOT-20200406.zip](https://github.com/andi34/photobooth/files/4439215/photobooth-SNAPSHOT-20200406.zip)

**Comment by md-20** [comment]
> 
> 
> It's easy to hide it if you are in fullscreen, but if you exit fullscreen without reloading the page the button would still be gone.

i think you could implement a toast message on pressing the button like " Please reload the page when you turn back to normal mode". Other option: Just writing "Please reload the page when you turn back to normal mode" after the option in admin panel

**Comment by md-20** [comment]
> 
> 
> Ready to use build:
> [photobooth-SNAPSHOT-20200406.zip](https://github.com/andi34/photobooth/files/4439215/photobooth-SNAPSHOT-20200406.zip)

Great! Sorry, i have a look later again, im busy now

**Comment by andi34** [comment]
> > It's easy to hide it if you are in fullscreen, but if you exit fullscreen without reloading the page the button would still be gone.
> 
> i think you could implement a toast message on pressing the button like " Please reload the page when you turn back to normal mode". Other option: Just writing "Please reload the page when you turn back to normal mode" after the option in admin panel

I'll think about it. But if you have time feel free to implement and send a PR.

**Comment by md-20** [comment]
It looks great and works nicely, thank you! Well done! I think you can keep it that way, the button doesn't matter, its pretty!
![Screenshot_181](https://user-images.githubusercontent.com/30606389/78608324-02103980-7861-11ea-9d71-ffa8dd41034d.jpg)

**Comment by andi34** [comment]
Great!
Let me know if you find any issues, the package now also used a different translation library which supports a fallback if a translation is missing. Also i18n-translator can be used to translate Photobooth.

For reference https://github.com/andi34/photobooth/issues/41

Edit:
Forgot to mention that I've tried to enable fullscreen automatically at accessing the page, but it needs a user action to enable it (a virtual button click is not allowed for security reasons).
