### ISSUE TITLE
[BUG]: When sending E-Mail and "Send me a link to all pictures in the next few days" is enabled, no E-Mail is sent

### ISSUE THREAD

**Issue by talentlos** [andi34/photobooth#461]
### Describe the bug

When using the E-Mail feature with option "Send me a link to all pictures in the next few days" is enabled, no E-Mail will be sent, unless the checkbox is unchecked. Mail-Adresses are stored correct.

### Steps to reproduce the behavior

Use E-Mail-Feature in Gallery

### Expected behavior

When Checkbox "Send me a link to all pictures in the next few days" is enabled and Button "Send Mail" is pressed, mail-adress should be stored in file and E-Mail should be sent.

### Photobooth Version

latest dev

### Browser and browser version

all browsers

### Operating System

Raspberry Pi OS with desktop

### Did it work before?

Yes

**Comment by andi34** [comment]
Hey and thanks for the feedback. The button has the wrong text, it would need to be called "add address to database" or similar. It's not meant to send an email and should only be used if the single picture can't be send directly. I am going to adjust the button asap.

**Comment by andi34** [comment]
Description of the option from the manual at http://localhost/manual (also tooltip on hover):
> If enabled, entered email adresses get stored inside a database instead sending choosed picture directly. For example, this can be used to send a mail with all pictures or a link to an online gallery after the event.

**Comment by talentlos** [comment]
Ah okay – I missunderstood the feature! Thanks for fixing! 😊



Von: Andreas Blaesius
Gesendet: Mittwoch, 6. Juli 2022 19:00
An: andi34/photobooth
Cc: talentlos; Author
Betreff: Re: [andi34/photobooth] [BUG]: When sending E-Mail and "Send me alink to all pictures in the next few days" is enabled, no E-Mail is sent(Issue #461)

Description of the option from the manual at http://localhost/manual (also tooltip on hover:
If enabled, entered email adresses get stored inside a database instead sending choosed picture directly. For example, this can be used to send a mail with all pictures or a link to an online gallery after the event.
