### ISSUE TITLE
Photobooth Title konfigurierbar

### ISSUE THREAD

**Issue by tobiashaas** [andi34/photobooth#5]
Hey @andi34 ,
Vielen Dank dass du in letzter Zeit soviel für die Photobooth Software gemacht hast! 
Mich hat es sehr gefreut, da ich meine Box bald auf einer Hochzeit von meinem Kumpel einsetzen möchte ;-)

Meinst du es wäre möglich eine Art Titel einzubauen?
Also z.B 

Hochzeit von Max & Moritz am 12.12.12 ? 
Oder vielleicht sogar auch so etwas wie Filter wie man es von Instagram kennt, oder sogar eine Funktion um zb 3 oder 4 Fotos als Collage aufzunehmen? 

Das wäre sehr cool

Vielen Dank und ich freue mich von dir zu hören

**Comment by andi34** [comment]
Hey!
Klar ist ein Titel möglich "einzubauen". Privat gerade viel um die Ohren und wenig Zeit für PC Sachen... Wenns passt schaue ich aber gerne nach.
Nächste Woche kommt mein Raspberry 4 hoffentlich und da möchte ich natürlich auch als bald als möglich mit spielen.

Mit Collage: mit ImageMagick vllt umsetzbar.
https://imagemagick.org/script/montage.php

Beste Grüße

Andi

**Comment by tobiashaas** [comment]
Hi Andi, 
Super ich freue mich! 

Mein Rpi4 sollte morgen eintreffen <3

Das mit der Collage schaue ich mir mal an, danke 

Liebe Grüße und schönen Abend
Tobias

**Comment by andi34** [comment]
Im lang/de.js

```
"startScreen": "<h1>Photobooth<\/h1><h2>zur Hochzeit von Max und Moritz<\/h2> 12.12.12",
```

Reicht dir das?

Edit:
Ich hasse mobile Seiten...

**Comment by tobiashaas** [comment]
Schaue ich mir heute Abend mal an! Danke dir
Darf ich fragen warum du das überhaupt "mobil" anpasst?
Macht doch irgendwie keinen Sinn oder nicht? :-D 

Man benötigt ja eig nur den QR Code um an das Foto zu kommen, der rest wird ja an der PHotobooth selbst erledigt oder verstehe ich da was falsch :P

**Comment by andi34** [comment]
Ging ums antworten hier von mobil. 😛

**Comment by andi34** [comment]
Aber grundsätzlich: die Photobooth lässt sich mit meinem OnePlus 6 ziemlich gut bedienen. QR Code sieht nur nicht gut aus....

Anstelle von QR fände ich die Möglichkeit per Download button besser. Der Pi als AP eingerichtet reicht aus, könnte jeder der verbunden ist sein Bild runterladen. Kenne kaum wen, der QR nutzt....

**Comment by tobiashaas** [comment]
Ja QR ist so ne Sache.... Aber ich hab schon Kopfschmerzen wenn ich nur daran denke, dass sich die Leute erstmal mit der Box verbinden müssen :-D Das checken viele auch wieder nicht. Und dann denken die noch sie haben Internet.... Weil WLAN ja für die meisten Internet bedeutet xD xD
Bin mal gespannt wie das wird, bald wird sie getestet!

**Comment by tobiashaas** [comment]
> Im lang/de.js
> 
> ```
> "startScreen": "<h1>Photobooth<\/h1><h2>zur Hochzeit von Max und Moritz<\/h2> 12.12.12",
> ```
> 
> Reicht dir das?
> 
> Edit:
> Ich hasse mobile Seiten...

Ich hoffe ich komme heute dazu es zu testen! Cool wäre es wenn man das ganz Easy im Admin Panel ändern könnte :P ... Ich gebe dir Rückmeldung

**Comment by andi34** [comment]
Das sollte kein Problem sein das im Adminpanel konfigurierbar zu machen, am Ende halt nur im Zweifel schwierig, da es dann in allen Sprachen so ist wie eingestellt

**Comment by tobiashaas** [comment]
Hey Andi, jetzt habe ich das mal getestet und endlich gerafft wofür das genau ist :-D 
Klar, das ist natürlich fürs erste vollkommen okay ;-) 
Aber schön wäre ja wenn man das im Admin Menü ändern könnte - auch für alle Sprachen.

Damit kann ich aber erstmal arbeiten! Danke dir

**Comment by andi34** [comment]
Kein Thema :)

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/c8d329c382058f26a54d79e64c159a553b5f71af

Muss nur die config noch nen passenden Namen im Adminpanel bekommen.

Vorschläge?

**Comment by andi34** [comment]
Erledigt :)

https://github.com/andi34/photobooth/commit/572b86eeb419ef016117cd7703b063f606f4a0e5


![Screenshot_20190629-233038](https://user-images.githubusercontent.com/6080900/60389657-0899a580-9ac6-11e9-9a49-376e95a128ea.jpg)

**Comment by tobiashaas** [comment]
Gefällt mir sehr gut! Danke ;-)

**Comment by andi34** [comment]
Zu den filtern: bin dabei mit zu spielen, leider zu resourcen-hungrig... Dauert ewig... Mal sehen ob ich da was auf die Beine bekomme

**Comment by tobiashaas** [comment]
Super ich bin gespannt! Hab es mir auch mal angeschaut.... werde aber leider nicht schlau daraus ... bin leider absolut kein Coder ... Würde dir da gerne helfen ... bin aber ganz am Anfang :-(

**Comment by andi34** [comment]
Graustufen Bild, Sepia und negativ könnte ok sein. Hatte aber größeres vor was leider, zumindest auf dem Pi3, nicht Umsetzbar ist (nicht gut ne Minute oder länger auf ein Bild zu warten)

**Comment by andi34** [comment]
Das Ding ist:
Wenn mans ausdrucken will direkt ist Filter ok.
Wenn man's runterladen kann: Filter kann jedes Handy.
Und Filter kann man jeder Zeit im Nachhinein.

Klar, ne lustige Spielerei im Zweifel, aber muss auch praktikabel sein am Ende und der Pi ist eben kein High-Ende-Gerät.

Auf nem festen Linux PC mag das ganze ohne jegliche Probleme klappen.

Muss Mal sehen, was man wie am geschicktesten macht ... Bin mir da unschlüssig, auch wie viel Zeit ich investiere in die Option um sie anständig hinzubekommen

**Comment by tobiashaas** [comment]
Da gebe ich dir vollkommen recht, dann lieber ohne Filter als ne Minute auf das Foto zu warten... 
Kannst du mir mal sagen was ich ins Terminal reinhacken kann um das zu testen? 
Dann sag ich dir mal wie lange der RPi4 dafür braucht ;-)

**Comment by andi34** [comment]
```
sudo apt-get install imagemagick

convert myjpg.jpg -bordercolor white -background black +polaroid newjpg.jpg

convert myjpg.jpg -charcoal 2 Bla.jpg

convert myjpg.jpg -type Grayscale blaa.jpg

convert myjpg.jpg -set colorspace RGB -sepia-tone 80% blaaa.jpg
```
Nur als bsp

**Comment by tobiashaas** [comment]
Also wenn das Foto in der Auflösung nicht mega groß ist, läufts ganz flüssig.
In Voller Auflösung - was meine Canon 600d hergibt - hängt sich der RPi4 irgendwann auf... 
50% kleiner gehts super

**Comment by andi34** [comment]
Hatte auch schon überlegt die Bilder einfach in der Größe vorher zu beschränken und dann umzuwandeln. Ist aber auch am Ende eher unbefriedigend...

```
convert myjpg.jpg -resize 50% myjpg.jpg

convert myjpg.jpg -bordercolor white -background black +polaroid myjpg.jpg
```
Das sollte dann auch am Ende immer das Original überschreiben.

Oder aber auch
```
convert myjpg.jpg -resize 1080 myjpg.jpg

convert myjpg.jpg -bordercolor white -background black +polaroid myjpg.jpg
```

**Comment by andi34** [comment]
Glaub ich habe eine "bessere" Alternative für Standard Filter gefunden die ich die Tage testen werde.

Imagemagick hat generell auch Probleme aus PHP raus ausgeführt zu werden...

Ggf später die php Version nochmal mit installieren und schauen ob es damit geht. Den Polaroid Effekt finde ich nämlich ziemlich nice an sich.

**Comment by tobiashaas** [comment]
Also diesen Polaroid Effekt finde ich auch ziemlich nice! Der hat's mir echt auch angetan.
<3

Die Alternative wäre dann GD oder?

**Comment by andi34** [comment]
Sepia, negativ und graustufen Bilder passt.
Muss nur den Code noch schick hinbekommen... und danach ins Admin panel vorerst. Vermutlich....

**Comment by koenigd79** [comment]
Hi
Filter fände ich auch genial. 
Habe auf Andre Rina weibseite in den Kommentaren folgende Seite gefunden:
https://www.reinhard-rebernig.at/website/websites/fotokasterl/#
da finde ich ist das ganz toll umgesetzt mit den FIltern, der Autor Reinhard Rebernig würde auch teile seines Codes hergeben, ggf. erspart euch das ne menge Arbeit. Ich selber kann leider nicht wirklich programmieren und lese hier aber interessiert überall mit, da ich die Fotobox ne super Sache finde.
Hoffe es hilft....
Gruß Daniel

**Comment by andi34** [comment]
Schon gesehen und in Kontakt getreten vor 2 Tagen. Muss Mal sehen was davon auf dem Pi läuft. Er lässt mir Code-Teile demnächst zukommen.
Imagemagick z.B. ist zu resourcen-hungrig... 
Da ich selbst noch Neuling mit PHP etc bin werde ich ggf. Hilfe brauchen, vor allem wenn der Code sauber seien soll (Code Qualität ist mir wichtig).

**Comment by koenigd79** [comment]
Super,

ggf. hilft auch das noch weiter:

https://github.com/zaachi/PHP-Instagram-effects

damit habe ich vor einiger Zeit mal expiremtiert, aber kam nicht richtig zum Ergebnis mangels  php Kenntnis.

**Comment by andi34** [comment]
Danke, habe schon was am laufen mit Standardfiltern, bin aber Codeseitig noch nicht ganz zufrieden und muss dazu auch noch alles ins Adminpanel packen bis ich eine bessere Lösung habe.

Kann also noch etwas dauern bis ich da was publiziere...

**Comment by andi34** [comment]
Im übrigen hat André auch meine Pullrequest gemerged. Abgesehen von E-Mail ist also alles auch bei ihm jetzt im Source.

Email muss ich noch testen, noch nicht zu gekommen bisher 😆

**Comment by andi34** [comment]
@tobiashaas habe nun die Filteroption soweit fertig. Reinhard Rebernig hat mir seine snippets zur Verfügung gestellt und geholfen es auch zum laufen zu bekommen mit der sidebavbar.

Werde ich demnächst dann hochladen für jedermann.

Kannst du zufällig https://github.com/andi34/photobooth/issues/11 bestätigen?

Edit:
Erledigt: https://github.com/andi34/photobooth/commit/0a8c874e5ad5fa93f9c1eb61b9b8746954d2f313

**Comment by tobiashaas** [comment]
Werde ich heute mal testen! 😉

**Comment by andi34** [comment]
@tobiashaas hab den Fehler gefunden. Habe oben den Commit gepostet.

**Comment by tobiashaas** [comment]
Danke für die Info! Hab es eben gesehen ;-)
