### ISSUE TITLE
External Monitor Touch

### ISSUE THREAD

**Issue by fui86** [andi34/photobooth#54]
Hi, i want to connect my raspberry to a monitor with HDMI for video and USB for touchscreen.
Is it compatible with any monitor?
I'm looking this model:
https://www.ebay.it/itm/81cm-32-ELO-ET3243L-HD1080-MONITOR-SAW-TOUCH-TOUCHSCREEN-E000732-WANDMONITOR/273770200955?hash=item3fbdf9bf7b:g:APoAAOSw~llcIJqn

**Comment by andi34** [comment]
You'll have to ask the touchscreen seller if it's compatible with a raspberry pi. Some touchscreens need special driver.
