### ISSUE TITLE
[survey] Gallery button position

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#65]
# Survey

Place Gallery buttons on top or center on the bottom by default?

Please let me know your opinion!

## Examples of buttons on bottom center
**UPDATED 14.06.2020**

On mobile devices (width <1024px) buttons left aligned, else some buttons are out of view

### Desktop view
![Screenshot_2020-06-14_11-39-52](https://user-images.githubusercontent.com/6080900/84590124-1f9aea00-ae34-11ea-9005-a17548467ea6.png)

![Screenshot_2020-06-14_11-39-44](https://user-images.githubusercontent.com/6080900/84590127-20cc1700-ae34-11ea-9f5c-7a13cdebaa97.png)

### Mobile view on a OnePlus6
![Screenshot_20200614-113959](https://user-images.githubusercontent.com/6080900/84590106-f9754a00-ae33-11ea-93fc-4cba062e8b74.jpg)

![Screenshot_20200614-114005](https://user-images.githubusercontent.com/6080900/84590107-fa0de080-ae33-11ea-97ed-3dbe3c54f66b.jpg)

**Comment by michi-93** [comment]
Hi! 
In my opinion this is much better to handle than the buttons before! 
Good job
