### ISSUE TITLE
Gallery: Close opened picture if photo/collage is triggered

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#73]
**Describe the bug**
If a picture is opened in gallery and a picture is taken via buzzer/keycode the countdown and everything following is not visible.

**To Reproduce**
Define a keycode to trigger a picture via admin panel.
Take a picture.
Open gallery and click on a thumbnail to view the picture.
Trigger a photo via defined keycode.

**Environment (please complete the following information):**
 - OS: Raspbian OS

**Photobooth**
- Did it work before? 
No
- Which version of Photobooth are you using?
2.5.0

**Additional context**
Picture is a pswp element. We need to hide it if a picture is taken and make it visible again.

**Comment by andi34** [comment]
@sualko you've an idea how to fix that?

**Comment by sualko** [comment]
Hi Andy, currently I can't help because I didn't use it for quite some time, because I'm busy with other things.

**Comment by sualko** [comment]
Maybe a quick idea: You should register an event handler in https://github.com/andi34/photobooth/blob/dev/resources/js/photoinit.js which is listening for the trigger key and call `gallery.close()`. Your linked commits will result in a huge mess. Maybe you can also make `gallery` globally callable, but that would be the nasty way.

**Comment by andi34** [comment]
It's the `pswp` class which has the picture opened.
I somehow need to use the `pswp.close()` from https://github.com/andi34/PhotoSwipe/blob/master/dist/photoswipe-ui-default.js#L734

But didn't got it working so I've had to remove all the classes this way (else it'll add the other classes a second time if a picture is opened)....

Edit:
https://github.com/andi34/PhotoSwipe/blob/master/dist/photoswipe-ui-default.js#L256

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/pull/74/commits/1804d3cb12565e071790002c8710daefb58fba2b

Ok, this works too 🙈
Thanks @sualko !

**Comment by andi34** [comment]
Well... Seems like my cache had a false positive result. Does not work this way... Need to play around again
