### ISSUE TITLE
gallery standalone

### ISSUE THREAD

**Issue by andi34** [andi34/photobooth#8]
Make gallery a own page without button to close and without ability to take pictures.

Idea: Move current index.php e.g. to /photobooth (other recommendations welcome, maybe /takepic or /capture)

Other ways possible too (using a cookie?).

**Comment by andi34** [comment]
@f4bsi gerne einfach ne PR zu mir wenn du deinen Teil findest :) dann schaue ich mal drüber. Vielen Dank schon Mal :)

**Comment by F4bsi** [comment]
Looking into it right now :)

**Comment by andi34** [comment]
In v2.0.0-alpha, `localhost/gallery.php`
