### ISSUE TITLE
Collage: invaild file provided

### ISSUE THREAD

**Issue by nocomment-bln** [andi34/photobooth#81]
Hallo Andi34,

die Collagen Funktion funktioniert bei mir leider nicht.

Es werden alle 4 Fotos ausgelöst und beim zusammenrechnen kommt dann das:

![image](https://user-images.githubusercontent.com/37557661/88437995-f47ac180-ce07-11ea-8ddd-078ddcfc4dd7.png)

Hast du eine Idee woran es liegen könnte ?

Installiert ist: 2.7.0 auf nem Raspi 4

**Comment by andi34** [comment]
Schau ich mir nach dem Aufstehen an.
Hast du Mal den Browser cache geleert? Oder über ein Privates/Incognito Fenster geöffnet und versucht?
Ist über F12 was in der Konsole noch sichtbar?

**Comment by andi34** [comment]
Problem gefunden. Ich schaue gerade nach einer Loesung

**Comment by andi34** [comment]
v2.7.1 behebt das Problem und ist ab jetzt verfuegbar.
Vielen Dank fuers melden des Fehlers!

**Comment by nocomment-bln** [comment]
Danke Andi! Super schneller Support! Gute Arbeit!
