### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by nocomment-bln** [andi34/photobooth#82]
Hallo Andi,
super dass du das Projekt so gut weiterentwickelst und am Ball bleibst! Danke hierfür!

Hier kommen ein paar Ideen und Anmerkungen.

**1.** Wenn man auf Drucken klickt, sollte man einstellen können dass mehrere Abzüge gedruckt werden.
Beispiel: Eine Gruppe mit 3 Leute macht zusammen ein Foto. Wenn man jetzt auf Drucken drückt kommt nur eins raus.
Man sollte die Funktion aktivieren/deaktivieren können. Eventuell macht auch ein Limiter sinn, sodass die ggf. betrunken Menschen auf einer Hochzeit da nicht 50 einstellen und drucken klicken. Vielleicht auch Buttons nachdem man Drucken geklickt hat: 1x Drucken .2x Drucken 3x Drucken oder 4x Drucken. Das muss ja auch schön aussehen, da habe ich noch keine Ahnung. Das Feature wäre cool! 

**2.** Die Collage Funktioniert jetzt super. Danke nochmal dafür!
Ich würde mir wünschen, dass die Collage auch noch wie folgt aussehen würde.

![image](https://user-images.githubusercontent.com/37557661/88454641-502d6500-ce71-11ea-8230-02b6ff2cd05e.png)

Die Fotos untereinander unten ggf. unten ein Logo.

**3.** Papierauswahl Einstellung. Sehr nett wäre es, wenn man das Papier auswählen könnte.

Ich möchte meinen Photobooth vor Ort gerne als "Drucker Photobooth" nutzen und dann fehlen diese Features.
Natürlich ist das herrunterladen der Fotos etc. auch wirklich sehr top!

Zu meiner Config.

Ich nutze
- Raspi 4 - 4GB RAM
- Kamera: Canon 6D
- Blitz: Profoto B1 
- Drucker:   [mitsubishi cp d70](https://www.amazon.de/Mitsubishi-Electric-CP-D70DW-Fotodrucker-Farbstoffsublimation/dp/B00AFZ8MQOl)

Was hältst du von den Punkten ?
Ich helfe gerne soviel ich kann.

Lieben Gruß aus Berlin
Patrick

**Comment by andi34** [comment]
Hey und danke für die Vorschläge.

Für den Print command ließe sich natürlich eine Schleife einbauen, würde aber bedeuten das eine Abfrage der Anzahl beim Druecken auf den Druck Button abgefragt werden muss.
Denke das bekomme ich hin , braucht aber Zeit.

Das Collage Layout anpassen habe ich schon Mal versucht, aber gescheitert. Vielleicht schaue ich mir das nochmal an, ansonsten freue ich mich natürlich wenn das jemand anderes erledigen kann.
Es gab Mal eine Lösung über Imagemagick, aber Imagemagick lief generell nicht gerade flott auf meinem Pi weshalb ich eine Umsetzung über GD versucht habe.
Siehe auch https://github.com/andreknieriem/photobooth/issues/164

Bezüglich der Papierauswahl:
Willst du den Schacht definieren je nach Bildformat? Ansonsten kannst du ja über CUPS alles für den Drucker einstellen.

Beste Grüße

Andi
