### ISSUE TITLE
Optional: Raspberry Pi (HQ) cam at install choosable

### ISSUE THREAD

**Issue by Nie-Oh** [andi34/photobooth#97]
Hallo Andi,

Danke für die tolle Arbeit und ständige Weiterentwicklung. Ich hätte nie gedacht, das man an einer Fotobox immer noch ein neues Feature benötigt. 

Heute habe ich einmal eine Bitte:

Es wäre toll, wenn man im Setup zwischen GPhoto und Raspbery Cam wählen könnte.
Wenn man die RaspiCam verwendet, muss man doch kein gPhoto installieren.

Ausserdem könnte man dan auch gleich die Befehle zum Auslösen der Bilder in das Admin Panel eintragen.

Gruß
Steffen

**Comment by andi34** [comment]
Ich schau mir das an sobald ich Zeit habe, hab auch schon eine Idee dazu.

Für künftige Feature requests:
Bitte immer das Feature request template benutzen :)

**Comment by andi34** [comment]
```
wget https://raw.githubusercontent.com/andi34/photobooth/fix/97/install-raspbian.sh
sudo bash install-raspbian.sh
```
This should work fine. Can you please test and give feedback?
I've not removed gphoto2 as it doesn't harm and makes it easy to switch to an DSLR later.
